name: Release
'on':
  push:
    branches:
      - alpha
jobs:
  release:
    uses: traverson/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
